
#ifndef _CORE_DEFINES_H_
#define _CORE_DEFINES_H_

#define DESIRED_FPS 60.0

#define DEVICE_ORIENTATION_L_RIGHT 0
#define DEVICE_ORIENTATION_L_LEFT 1

#define SCREEN_SIZE_SMALL  0
#define SCREEN_SIZE_NORMAL 1
#define SCREEN_SIZE_LARGE  2
#define SCREEN_SIZE_XLARGE 3

#define STR_DEFAULT_TEXTURE_EXTENTION ".tga"
#define STR_DEFAULT_SOUND_EXTENTION ".wav"

#define FLAG_MODEL_TEXTURE 0x00000001

#define CONTENT_PARSE_SEPARATORS " \n\r=\t\","

#define FOV_DEFAULT 90.0f
#define VIEW_RANGE_DEFAULT 1000000.0f


#endif
